import styles from "../styles/Home.module.less";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Footer } from "./Footer";

// let bc1 = [];
// const how = (arr) => {
// for (let obj in arr) {
//   bc1.push(arr[obj].productCategoryId)
// }
// bc1 = bc1.reduce((x, index) => (x[index] = (x[index] || 0) + 1, x), {})
// return bc1
// };
// console.log(how(bc))

export const MainComponent = ({ children }: any) => {
  return (
    <>
      <Head>
        <title>Happy apple</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="app">
        <div className={styles.app__header}>
          <div className={styles.app__header__logo}>
            <Link href="/">
              <Image alt="logo" width={150} height={150} src="/6.png" />
            </Link>
          </div>
          <div className={styles.app__header__happy}>
            <Link href="/">
              <h1>Happy Apple</h1>
              <h2>Продажа/обмен техники Apple</h2>
            </Link>
          </div>
        </div>
        <div className={styles.app__main}>{children}</div>
        <div className={styles.app__footer}>
          <Footer />
        </div>
      </div>
    </>
  );
};
